apiVersion: v1
kind: Service
metadata:
  name: risk-ident-apache
spec:
  selector:
    app: risk-ident-apache
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
